name: Semgrep SAST Scan

# Trigger the scan ONLY on manual code changes
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  semgrep:
    name: Security Scan
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    container:
      image: semgrep/semgrep:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: semgrep scan --config auto